## Set nighttime value for Health Graphs

  - alias: 'Set Nighttime input'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      entity_id: input_number.nighttime
      service: input_number.set_value
      data:
        value: 20
        
  - alias: 'Set Daytime input'
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:45:00"
    action:
      entity_id: input_number.nighttime
      service: input_number.set_value
      data:
        value: 0
        
## Set custom theme on startup
  - alias: 'System - Set Custom Theme at Startup'
    initial_state: 'true'
    trigger:
      platform: homeassistant
      event: start
    action:
      service: frontend.set_theme
      data:
        name: slate
 
  - alias: ui_sound_on
    trigger:
    - platform: state
      entity_id:
        ['light.door', 'light.stairs_2', 'light.bed', 'light.bedroom_roof', 'light.toilet_2', 'light.toilet_1', 'light.plant_table', 
        'light.table', 'light.couch', 'light.kitchen_4', 'light.kitchen_3', 'light.kitchen_2', 'light.kitchen_1', 'light.roof_plants',
        'light.roof_garden', 'switch.speakers_vol_up', 'switch.speakers_vol_down', 'switch.power', 'switch.speakers_input',
        'light.balcony','light.study']
      from: 'off'
      to: 'on'
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.tablet
        media_content_id: /local/ui/sound/on.m4a
        media_content_type: music

  - alias: ui_sound_off
    trigger:
    - platform: state
      entity_id:
        ['light.door', 'light.stairs_2', 'light.bed', 'light.bedroom_roof', 'light.toilet_2', 'light.toilet_1', 'light.plant_table', 
        'light.table', 'light.couch', 'light.kitchen_4', 'light.kitchen_3', 'light.kitchen_2', 'light.kitchen_1', 'light.roof_plants',
        'light.roof_garden', 'switch.speakers_vol_up', 'switch.speakers_vol_down', 'switch.power', 'switch.speakers_input',
        'light.balcony','light.study']
      from: 'on'
      to: 'off'
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.tablet
        media_content_id: /local/ui/sound/off.m4a
        media_content_type: music

  - alias: ui_sound_popup
    trigger:
      platform: event
      event_type: call_service
      event_data: 
        domain: browser_mod
        service: popup
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.tablet
        media_content_id: /local/ui/sound/popup.m4a
        media_content_type: music
        
  - alias: ui_sound_view
    trigger:
      platform: state
      entity_id: sensor.tablet_view
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.tablet
        media_content_id: /local/ui/sound/popup.m4a
        media_content_type: music     
          
          